[tool.poetry]
name = "ascifight"
version = "0.1.0"
description = ""
authors = ["serbitar <serbitar@sessionmob.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.89.1"
pydantic = "^1.10.4"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
structlog = "^22.3.0"
context-logging = "^1.1.0"
toml = "^0.10.2"
pillow = "^9.5.0"
flask = "^2.2.3"


[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^23.1.0"
types-toml = "^0.10.8.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
