[server]
pre_game_wait = 5
tick_wait_time = 5
log_dir = "logs"
scores_file = "scores.log"

[game]
map_size = 15
max_score = 3
max_ticks = 200
score_multiplier = 1
home_flag_required = false
walls = 0
actors = ["Runner"]

[[teams]]
name = "Team 1"
password = "1"

[[teams]]
name = "Team 2"
password = "2"

[[teams]]
name = "Team 3"
password = "3"

[image]
size = 800